---

- name: Install packages
  npm:
    name: pm2
    global: yes
    version: "{{ pm2_version | default(omit) }}"
  notify: restart pm2

- name: setting startup script
  command: >
    pm2 startup {{ pm2_startup }} -u {{ pm2_user }} --hp {{ pm2_user_home }}
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin"
